export { API_BASE, type ApiResponse, get, post, put, patch, del } from './api';
export { authService, type User, type AuthPayload, type RegisterData } from './auth.service';
export { cartService, type CartItem, type Cart } from './cart.service';
export { catalogService, type Product, type Sku as CatalogSku, type ProductFilters, type ProductsResponse } from './catalog.service';
export { favoritesService, type FavoriteProduct, type FavoriteItem } from './favorites.service';
export { orderService, type Order, type CreateOrderData } from './order.service';
export { userService, type UserProfile } from './user.service';
export { dashboardService, type DashboardMetrics, type InventoryPerformance, type Promotion as DashboardPromotion } from './dashboard.service';
export { promotionService, type Promotion } from './promotion.service';
export { inventoryService, type InventoryNode, type InventoryStock, type Sku as InventorySku, type ProductInventory, type SkuNode } from './inventory.service';
